coot/release
input-output-hk/nothunks pull request #38
Opened 2023-10-29 10:14 UTC by coot

- Bump version
- CI: enable merge queue

2023-10-29 10:16 UTC, coot commented
First merge #34.

2023-11-03 16:42 UTC, bolt12 requested changes

2023-11-03 16:42 UTC, bolt12 commented on CHANGELOG.md
> +## 0.1.5 -- 2023-10-29
Add a "Next version" section

2023-11-03 17:26 UTC, coot commented on CHANGELOG.md
> +## 0.1.5 -- 2023-10-29
Fixed.

2023-11-06 09:39 UTC, merged